name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Подготовка репозитория
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: sermildev/telegram-bot:v0.1

    - name: Деплой на удаленный сервер
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER_HOST }}
        username: ${{ secrets.REMOTE_SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          docker pull sermildev/telegram-bot:v0.1
          docker stop telegram-bot || true
          docker rm telegram-bot || true
          docker run -d --restart always -p 80:80 --name telegram-bot -e BOT_TOKEN sermildev/telegram-bot:v0.1
