name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Подготовка репозитория
      uses: actions/checkout@v2

    - name: Логин в Docker Hub (или другом реестре)
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Сборка Docker-образа
      run: docker build -t telegram-bot:v0.1 .  
      
    - name: Пуш в Docker Hub
      run: docker push sermildev/telegram-bot:v0.1

    - name: Деплой на удаленный сервер
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER_HOST }}
        username: ${{ secrets.REMOTE_SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull sermildev/telegram-bot:v0.1
          docker stop telegram-bot || true
          docker rm telegram-bot || true
          docker run -d -p 80:80 --name telegram-bot -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} sermildev/telegram-bot:v0.1
